### ISSUE TITLE
ModuleNotFoundError: No module named 'libml'

### ISSUE THREAD

**Issue by varunnair18** [google-research/mixmatch#1]
Thank you for putting together this repository of Mixmatch, I enjoyed reading the paper. Upon trying to follow your installation, I ran into the following error: 
![image](https://user-images.githubusercontent.com/15525087/59103867-4de80e80-8930-11e9-96f1-dc0dda30e400.png)

I haven't been able to find an installation of libml available through anaconda or pip, what would you recommend I do?

Thanks!

**Comment by david-berthelot** [comment]
Hello, this is because you need to setup your python path to accept the root of the project:
```
export PYTHONPATH=$PYTHONPATH:.
```

I update the README to account for your question, let me know if it's clear now.

**Comment by varunnair18** [comment]
That did the trick, thank you for the help!
