### ISSUE TITLE
Why do you use 'activate_before_residual'?

### ISSUE THREAD

**Issue by CoinCheung** [google-research/mixmatch#11]
Hi, 

I am going through this codebase carefully, and I find that the wide-resnet you used is slightly different from the model proposed in the paper. In your model, the last two stages did not include the bn-relu in the residual blocks as in the paper (which makes the shortcut clean). What is the reason of using this structure please? Does this structure help to boost the unsupervised performance ?

**Comment by david-berthelot** [comment]
We took the code from Realistic Evaluation of SSL algorithm and just refactored it a bit:
https://github.com/brain-research/realistic-ssl-evaluation/blob/master/lib/networks.py

We didn't do any change to it with the purpose of improving accuracy.
