### ISSUE TITLE
The architecture for Cifar-100 dataset

### ISSUE THREAD

**Issue by wang3702** [google-research/mixmatch#12]
Could you please tell me the exact architecture for cifar-100? It stated that it has increased the width of the wide-resnet. What is the increased width of the new architecture. For the 28*2 architecture, it increased the number of filters from 16 to 32 to 64 to 128. What's your meaning that "it has 135 filters per layer"? Does it mean all convolution layer has 135 layers?
Thanks a lot!

**Comment by david-berthelot** [comment]
See how to reproduce tables in `runs` folder:
https://github.com/google-research/mixmatch/blob/master/runs/table1.sh

Basically we pass the option `--filters=135` (instead of 32), as you can see in `libml/models.py` the layers grow proportionally to that number in the resnet architecture (and in other architectures too).

**Comment by wang3702** [comment]
That's to say, it starts from 135, then 270, then 405 and 540(for 4 blocks). If my understanding is correctly, I will close the issue. Thanks!

**Comment by wang3702** [comment]
Sorry for my incorrect calculation. Here the number of filters should from 135,270,540,1080. Is that Correct?

**Comment by wang3702** [comment]
I have checked that: that's around Total params: 104.6074160000M. In your paper, it's around 26 million parameter. Could you please explain more detailed?

**Comment by wang3702** [comment]
I figured out:
it's 16, 135,270,540.
Total number of params: 26.1161800000M
Is my understanding correct?

**Comment by david-berthelot** [comment]
I don't recall the exact number, in the paper we quoted 26M. When you run the code you can see the size of the network parameters layer by layer before training start.
