### ISSUE TITLE
What is the purpose of creating the "-map.json" file in scripts/create_split.py and eval_labeled/eval_unlabeled in libml/data.py?

### ISSUE THREAD

**Issue by varunnair18** [google-research/mixmatch#13]
Does the "-map.json" file have any purpose in the training process at all? I see that it stores the ids of images that are used as unlabeled data, but cannot find any usage of it anywhere in the repository.

Can you also explain why you read from the "-label.tfrecord" and "-unlabel.tfrecord" twice (for train_labeled, train_unlabeled, eval_labeled, eval_unlabeled respectively) in libml/data.py? Is this because you fetch a sample of images for training and then later fetch the same set of samples to compute evaluation metrics?

**Comment by david-berthelot** [comment]
JSON is just for information, it's not used.
For the second question you guessed right.

**Comment by varunnair18** [comment]
Good to know, thank you for helping!
