### ISSUE TITLE
STL 10 settings

### ISSUE THREAD

**Issue by wang3702** [google-research/mixmatch#15]
Hi, 
Just to make sure, considering you achieved state-of-art performance on STL-10. I want to make sure if you used the unlabeled data or not in your current best result with all 5000 labels.

Thanks a lot!

**Comment by wang3702** [comment]
Could you please have a check? Thanks

**Comment by david-berthelot** [comment]
We only use the unlabeled data that is part of the STL10 dataset. 
Is your question about external data? No external data was used, only STL10.

**Comment by varunnair18** [comment]
To add to the above question @david-berthelot, was there any reason that you didn't run experiments on STL-10 using the prior semi-supervised methods as you did for CIFAR-10 and SVHN?

As a student, I was wondering if it is a common research practice to not evaluate prior methods on benchmarks that were not in the respective original work.

**Comment by wang3702** [comment]
@david-berthelot Thanks a lot! That's my question, I think you used the unlabeled part in STL. Congratulations to be SOTA in STL10. I just noticed that thus have this question!
