### ISSUE TITLE
Number of validation samples

### ISSUE THREAD

**Issue by hankook** [google-research/mixmatch#20]
I found that scripts in the `runs/` directory use only one sample for validation, e.g., [here](https://github.com/google-research/mixmatch/blob/master/runs/table5.sh#L21).

The paper also said that the median error rate of the last 20 checkpoints is used when reporting, which means that no validation is required. Is this the reason why the code uses only one validation sample? 

Am I correct? If not, how many validation samples are used?

**Comment by david-berthelot** [comment]
Yes that is correct, we used 1 because the code doesn't allow for 0. Also we didn't really tune per dataset, we used almost the same parameters for everything.

**Comment by hankook** [comment]
Thanks for your reply and this public repo :)
