### ISSUE TITLE
When will Remixmatch (ICLR'20) be available?

### ISSUE THREAD

**Issue by jason718** [google-research/mixmatch#23]
I recently read this amazing following paper ReMixMatch. The arxiv version points to an empty github  repo. I am wondering that when will the code be made available? Is it possible that we can access it soon so that I can use it for my ICML submission?

**Comment by david-berthelot** [comment]
The repo pointed by the arxiv should contain the code now:
https://github.com/google-research/remixmatch

**Comment by jason718** [comment]
@david-berthelot  Awesome! thanks!

**Comment by guotong1988** [comment]
Thank you!
