### ISSUE TITLE
Working with higher resolution images

### ISSUE THREAD

**Issue by hzhz2020** [google-research/mixmatch#37]
Dear Authors 

thanks for your inspiring works. I would like to try MixMatch or FixMatch on higher resolution images. I think your current implementation is already compatible with images with any resolutions? as long as it is RGB images. Is that correct? Any other comments or suggestions that you can give on adapting MixMatch or FixMatch to higher resolution images?

Thanks a lot!

**Comment by carlini** [comment]
There is nothing fundamental to low resolution images. For example, we have FixMatch training on ImageNet and that repository contains an implementation.
