### ISSUE TITLE
what is the proper behavior of consistency loss

### ISSUE THREAD

**Issue by dlnewbie-h** [google-research/mixmatch#40]
Dear authors
Thanks for your great work! 

My question is what is the expected/proper behavior of the consistency loss over the course of training? Is it supposed to go down smoothly like the labeled loss term? or Is it supposed to oscillate around certain level during the training?

Thanks!

**Comment by david-berthelot** [comment]
It's been two years since I've written the code and ran the experiments and I don't recall.
Probably the simplest way to answer your question would be to run it on cifar10 (since it's relatively fast): https://github.com/google-research/mixmatch/blob/master/runs/table5.sh
