### ISSUE TITLE
mixmatch

### ISSUE THREAD

**Issue by lichunlei111** [google-research/mixmatch#8]
Hello, I am very inspired to read your thesis, but when I run the code, I find that the code is missing files. Can you send me the complete code? Appreciate it!

**Comment by david-berthelot** [comment]
What files are missing?

**Comment by sndnyang** [comment]
I can run this code. Everything is there...

**Comment by david-berthelot** [comment]
Thanks for the clarification. I am closing this for now until further information is available.
